
models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: email
        tests:
          - not_null # This test will pass now because of our COALESCE statement!

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_inventory
    columns:
      - name: inventory_id
        tests:
          - unique
          - not_null
      - name: stock_quantity
        tests:
          - not_null
          # This ensures our GREATEST() logic worked and nothing is below 0
          - accepted_values:
              values: [">= 0"] 
              quote: false

  - name: stg_sales
    columns:
      - name: transaction_id
        tests:
          - unique # This will fail if our QUALIFY deduplication didn't work
          - not_null
      - name: customer_id
        tests:
          - not_null
          # Referential integrity: Ensure sales are mapped to real customers
          - relationships:
              to: ref('stg_customers')
              field: customer_id